[workspace]
members = ["crate/*"]
default-members = ["crate/front"]
resolver = "2"

[workspace.package]
version = "2.0.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
strip = true
