[workspace]
members = ["crate/*"]
default-members = ["crate/front"]
resolver = "3"

[workspace.package]
version = "2.0.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2024"
rust-version = "1.95" # nixpkgs stable

[workspace.lints.rust]
rust_2018_idioms = "deny"
unsafe_code = "forbid"
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[profile.release]
codegen-units = 1
lto = true
strip = true
