[package]
name = "gefolge-wichteln"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
chrono = "0.4"
chrono-tz = "0.10"
clap = { version = "4", features = ["derive"] }
gefolge-web-lib = { path = "../lib" }
heliocron = { git = "https://github.com/fenhl/heliocron" }
itertools = "0.15"
peter-ipc = { path = "../peter-ipc" }
rand = { version = "0.10", features = ["thread_rng"] }
serenity = { version = "0.12", default-features = false, features = ["model", "rustls_backend"] }
sqlx = { version = "0.9", features = ["postgres", "runtime-tokio", "tls-rustls"] }
thiserror = "2"
wheel = { git = "https://github.com/fenhl/wheel", features = ["chrono"] }
